Repository sprint6-part4-team3/WouldYouWithMe, pull requests merged in 2024-08, with the labels that each got.

#49 💄 Design(#43): 자유게시판 상세보기 UI 구현
  public/assets/icons/icon-heart.svg
  public/assets/icons/index.ts
  public/assets/lotties/empty.json
  src/app/(board)/board/[boardId]/_components/add-comment/index.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/board-drop-down.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment-drop-down.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/empty-comment.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/index.tsx
  src/app/(board)/board/[boardId]/article.json
  src/app/(board)/board/[boardId]/comment.json
  src/app/(board)/board/[boardId]/page.tsx
  src/app/(board)/layout.tsx
  src/components/common/forms/textarea/index.tsx
  src/types/article/comment.ts
  src/types/article/index.ts
  src/utils/format-board-date.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#48 💄 Design(#38): 리스트 페이지
  public/assets/icons/icon-arrow-left.svg
  public/assets/icons/icon-arrow-right.svg
  public/assets/icons/icon-checkbox-primary.svg
  public/assets/icons/index.ts
  src/app/(list)/[teamId]/task-lists/[listId]/_components/index.ts
  src/app/(list)/[teamId]/task-lists/[listId]/_components/mock.json
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-lists-nav.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-nav.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/create-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  src/app/(list)/[teamId]/task-lists/error.tsx
  src/app/(list)/[teamId]/task-lists/layout.tsx
  src/app/[teamId]/_components/member/add-member-modal.tsx
  src/app/list/page.tsx
  src/components/common/buttons/add-list-modal-button/index.stories.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
  src/components/common/buttons/button/index.tsx
  src/components/common/icon-button/index.tsx
  src/components/common/index.ts
  src/components/common/modal/one-input-form/index.tsx
  src/utils/format-date.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#53 🚑️ Fix(#52): 인풋 자동완성 테두리 수정
  src/app/globals.css
  src/components/common/forms/input/index.tsx
Labels: 🚑️ Fix, 우선순위: Low 🐢

#51 💄 Design(#50): 팀 없을 경우 팀페이지 UI 구현
  public/assets/lotties/team-empty.json
  src/app/[teamId]/_components/empty/index.tsx
  src/app/[teamId]/_components/member/card.tsx
  src/app/[teamId]/_components/member/index.tsx
  src/app/[teamId]/_components/member/profile-modal.tsx
  src/app/[teamId]/_components/report/index.tsx
  src/app/[teamId]/page.tsx
  src/app/[teamId]/team.json
  src/types/group/index.ts
  src/types/user/index.ts
  src/utils/group-task-report.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#57 💄Design(#46) 할일 리스트의 상세페이지
  public/assets/icons/icon-comment.svg
  public/assets/lotties/nocomment.json
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/comment-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/comment-mock.json
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/comments-list.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/empty-comment.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-description.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-header.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-info.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-mock.json
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/page.tsx
  src/types/comments/index.ts
  src/types/task-detail/index.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#58 💄Design(#56) navbar ui 구현 후 레이아웃 연동
  public/assets/icons/icon-gnb-menu.svg
  public/assets/icons/index.ts
  src/app/(auth)/layout.tsx
  src/app/layout.tsx
  src/app/user.json
  src/components/common/nav-bar/index.stories.tsx
  src/components/common/nav-bar/index.tsx
  src/components/common/nav-bar/logo.tsx
  src/components/common/nav-bar/nav-component.tsx
  src/components/common/nav-bar/nav-sidebar.tsx
  src/components/common/nav-bar/team-dropdown.tsx
  src/components/common/nav-bar/user-dropdown.tsx
  src/types/user/index.ts
  tailwind.config.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#54 💄Design(#36): 팀 페이지 팀, 할 일 목록 UI 구현
  public/assets/icons/icon-done-cyan.svg
  public/assets/icons/icon-plus-cyan.svg
  public/assets/icons/index.ts
  public/assets/images/img-thumbnail-team.png
  public/assets/images/index.ts
  src/app/[teamId]/_components/team-card/index.tsx
  src/app/[teamId]/_components/todo-list/index.tsx
  src/app/[teamId]/_components/todo-list/progress-sign.tsx
  src/app/[teamId]/_components/todo-list/todo-list-card.tsx
  src/app/[teamId]/page.tsx
  src/utils/group-task-todo-list.tsx
Labels: 우선순위: Medium ☀️, 💄 Design

#63 💄 Design(#61): 팀 생성하기, 수정하기 페이지 UI 구현
  next.config.mjs
  public/assets/icons/icon-edit.svg
  public/assets/icons/icon-image-button-error.svg
  public/assets/icons/icon-image-button.svg
  public/assets/icons/index.ts
  src/app/(team-management)/[teamId]/edit/page.tsx
  src/app/(team-management)/_components/add-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/app/(team-management)/_components/image-input.tsx
  src/app/(team-management)/_components/name-input.tsx
  src/app/(team-management)/_components/submit-button.tsx
  src/app/(team-management)/addteam/page.tsx
  src/app/(team-management)/layout.tsx
  src/lib/schemas/team-manage/index.ts
  src/types/team-management/index.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#65 💄 Design(#64): 팀 참여하기 페이지 UI 구현
  src/app/(team-management)/_components/add-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/app/(team-management)/jointeam/_components/join-team-form.tsx
  src/app/(team-management)/jointeam/page.tsx
  src/lib/schemas/team-manage/index.ts
  src/types/team-management/index.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#70 🚑️ Fix: 모달 버그 및 버튼중복 오류 수정
  src/app/[teamId]/_components/member/add-member-modal.tsx
  src/app/[teamId]/_components/member/card.tsx
  src/app/[teamId]/_components/member/profile-modal.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
  src/components/common/drawer/index.stories.tsx
  src/components/common/drawer/index.tsx
  src/components/common/drop-down/trigger.tsx
  src/components/common/icon-button/index.tsx
  src/components/common/modal/index.stories.tsx
  src/components/common/modal/index.tsx
  src/types/modal-drawer/index.ts
Labels: 🚑️ Fix, 우선순위: High 🔥

#66 💄 Design(#62): 비밀번호 재설정 페이지 UI 구현
  src/app/(auth)/_components/reset-password-drawer.tsx
  src/app/(auth)/_components/reset-password-form.tsx
  src/app/(auth)/_components/reset-password-modal.tsx
  src/app/(auth)/_components/signin-form.tsx
  src/app/(auth)/_components/signup-form.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-up/action.ts
  src/app/(auth)/sign-up/page.tsx
  src/lib/schemas/auth/index.ts
  src/types/auth/index.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#73 💄 Design(#69): 게시글 작성 및 수정 페이지 UI 구현
  public/assets/icons/icon-plus-big.svg
  public/assets/icons/icon-x-big.svg
  public/assets/icons/index.ts
  src/app/(board-management)/_components/content-input.tsx
  src/app/(board-management)/_components/form-header.tsx
  src/app/(board-management)/_components/image-input.tsx
  src/app/(board-management)/_components/title-input.tsx
  src/app/(board-management)/_components/token-input.tsx
  src/app/(board-management)/board/[boardId]/edit/page.tsx
  src/app/(board-management)/create-board/page.tsx
  src/app/(board-management)/layout.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/create-team/page.tsx
  src/app/(team-management)/join-team/_components/join-team-form.tsx
  src/app/(team-management)/join-team/page.tsx
  src/lib/schemas/article/index.ts
  src/types/article/add-edit.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#74 💄 Design(#66): 마이리스트페이지 UI 제작
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/user/history/_components/mock.json
  src/app/user/history/_components/my-history-list.tsx
  src/app/user/history/layout.tsx
  src/app/user/history/page.tsx
  src/types/user-history/index.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#72 💄Design(#55): 할 일 등록
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/_components/add-task-form.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/_components/repeat-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/_components/repeat-sign.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/_components/select-button.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/_components/time-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/_components/weekly-option.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/create-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  src/app/(list)/[teamId]/task-lists/layout.tsx
  src/app/globals.css
  src/components/common/forms/error-message/index.tsx
  src/components/common/index.ts
  src/components/common/side-page/index.tsx
  src/lib/schemas/task/index.tsx
  src/types/task-list/index.ts
  src/utils/convert-string-array-to-num.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#77 💄 Design:(#71): 할 일 리스트 달력
  package.json
  public/assets/icons/icon-calendar-arrow-left.svg
  public/assets/icons/icon-calendar-arrow-right.svg
  public/assets/icons/index.ts
  src/app/(list)/[teamId]/task-lists/[listId]/_components/calendar-button.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/calendar.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-nav.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  yarn.lock
Labels: 우선순위: Medium ☀️, 💄 Design

#76 💄 Design(#67): 계정 설정 페이지 UI
  public/assets/icons/icon-edit.svg
  public/assets/icons/icon-secession.svg
  public/assets/icons/index.ts
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-drawer.tsx
  src/app/(auth)/_components/reset-password/reset-password-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-modal.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(auth)/_components/user-setting/cancel-user-drawer.tsx
  src/app/(auth)/_components/user-setting/cancel-user-modal.tsx
  src/app/(auth)/_components/user-setting/change-password-drawer.tsx
  src/app/(auth)/_components/user-setting/change-password-modal.tsx
  src/app/(auth)/_components/user-setting/email-input.tsx
  src/app/(auth)/_components/user-setting/image-input.tsx
  src/app/(auth)/_components/user-setting/name-input.tsx
  src/app/(auth)/_components/user-setting/password-input.tsx
  src/app/(auth)/_components/user-setting/user-setting-form.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/(auth)/user-setting/layout.tsx
  src/app/(auth)/user-setting/page.tsx
  src/components/common/buttons/float-button/index.tsx
  src/components/common/nav-bar/user-dropdown.tsx
  src/lib/schemas/auth/index.ts
  src/types/auth/index.ts
  tailwind.config.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#79 💄 Design(#78): 스크롤바 커스텀
  src/app/globals.css
  src/components/common/toast/container.tsx
Labels: 💄 Design, 우선순위: Low 🐢

#82 📦️ Chore(#80): React query 세팅
  package.json
  src/app/layout.tsx
  src/components/react-query-provider/index.tsx
  yarn.lock
Labels: 📦️ Chore, 우선순위: High 🔥

#75 💄 Design(#60): 랜딩 페이지 UI
  public/assets/images/img-landing-bottom.png
  public/assets/images/img-landing-icon-1.png
  public/assets/images/img-landing-icon-2.png
  public/assets/images/img-landing-icon-3.png
  public/assets/images/img-landing-main.png
  public/assets/images/img-landing-mockup-1.png
  public/assets/images/img-landing-mockup-2.png
  public/assets/images/img-landing-mockup-3.png
  public/assets/images/index.ts
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#90 ✨ Feat(#89): parallel route 폴더 구조
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/default.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/layout.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  src/app/(list)/[teamId]/task-lists/error.tsx
  src/app/(list)/[teamId]/task-lists/layout.tsx
Labels: ✨ Feat, 우선순위: High 🔥

#88 ✨ Feat(#84): axios Intercepter 설정
  src/lib/api/axios-instance.ts
  src/types/auth/index.ts
  src/utils/next-cookie.ts
  src/utils/next-redirect.ts
Labels: ✨ Feat, 우선순위: Low 🐢

#87 ✨ Feat(#85): 로그아웃 구현
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/layout.tsx
  src/components/common/index.ts
  src/components/common/nav-bar/index.stories.tsx
  src/components/common/nav-bar/user-dropdown.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/logo.tsx
  src/components/nav-bar/logout-drawer.tsx
  src/components/nav-bar/logout-modal.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/utils/next-cookies.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#91 ✨ Feat(#83): 팀 생성 / 수정 API 기능 구현
  public/assets/icons/index.ts
  public/assets/icons/loading-spinner.svg
  src/app/(auth)/login/actions.ts
  src/app/(team-management)/[teamId]/edit/page.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/app/(team-management)/_components/image-input.tsx
  src/app/(team-management)/_components/submit-button.tsx
  src/app/error.tsx
  src/app/not-found.tsx
  src/constants/error-message.ts
  src/constants/image-size.ts
  src/lib/api/group/create-group.ts
  src/lib/api/group/edit-group.ts
  src/lib/api/group/get-group-data.ts
  src/lib/api/image/image-upload.ts
  src/lib/schemas/team-manage/index.ts
  src/types/group/index.ts
  src/types/team-management/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#97 ✨ Feat(#93): navbar api 구현
  public/assets/images/img-planet.png
  public/assets/images/index.ts
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/[teamId]/_components/todo-list/todo-list-card.tsx
  src/app/layout.tsx
  src/app/user.json
  src/components/nav-bar/gnb-button.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/logo.tsx
  src/components/nav-bar/logout-drawer.tsx
  src/components/nav-bar/logout-modal.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/lib/api/auth/sign-in.ts
  src/lib/api/auth/sign-up.ts
  src/lib/api/nav-bar/get-user.ts
  src/utils/next-cookies.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#105 ✨ Feat(#103): jotai 사용 로그인 유저 정보 구현
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/board-like.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/logout-drawer.tsx
  src/components/nav-bar/logout-modal.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/lib/api/auth/sign-in.ts
  src/stores/recent-team-atom.ts
  src/stores/user-atom.ts
  src/types/user/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#101 ✨ Feat(#92): list page api
  package.json
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/add-task-form.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/repeat-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/repeat-sign.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/select-button.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/time-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/weekly-option.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/calendar-button.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/calendar.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/mock.json
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-lists-nav.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/add-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  src/components/loading/index.tsx
  src/lib/api/axios-instance.ts
  src/lib/api/task-lists/get-task-lists.ts
  src/lib/api/task-lists/get-tasks.ts
  src/types/task-list/index.ts
  yarn.lock
Labels: ✨ Feat, 우선순위: Medium ☀️

#110 ✨ Feat(#106): 비밀번호 재설정 api 구현
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-drawer.tsx
  src/app/(auth)/_components/reset-password/reset-password-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-modal.tsx
  src/lib/api/reset-password/reset-password.ts
  src/lib/api/reset-password/send-email.ts
  src/types/auth/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#114 🚑️ Fix:(#112): canlendar 높이 버그 수정 + 오늘 색 변경
  src/app/(list)/[teamId]/task-lists/[listId]/_components/calendar-button.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/calendar.tsx
Labels: 🚑️ Fix, 우선순위: High 🔥

#111 ✨ Feat(#104) 댓글 삭제/ 할일 완료 / 댓글입력
  .eslintrc.json
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comments-list.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/empty-comment.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-description.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-header.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-info.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/_components/comments/comments-list.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/_components/task-detail/task-content.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/_components/task-detail/task-description.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/comment-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/comment-mock.json
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/comments-list.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/comments/empty-comment.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-description.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-header.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/_components/task-detail/task-info.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/task-detail/[id]/page.tsx
  src/lib/api/task-comments/delete-comments.ts
  src/lib/api/task-detail/edit-task-detail.ts
  src/types/comments/index.ts
  src/types/task-detail/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#108 ✨ Feat(#100): 댓글 조회/작성/수정/삭제 API 기능 구현
  public/assets/images/img-background.png
  public/assets/images/img-spaceship.png
  public/assets/images/index.ts
  public/assets/lotties/empty.json
  src/app/(board)/board/[boardId]/_components/add-comment/index.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/add-comment.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment-delete-modal.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment-drop-down.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment-edit-mode.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/empty-comment.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/index.tsx
  src/app/(board)/board/[boardId]/comment.json
  src/app/(board)/board/[boardId]/page.tsx
  src/app/layout.tsx
  src/lib/api/board-comment/create-comment.ts
  src/lib/api/board-comment/delete-comment.ts
  src/lib/api/board-comment/edit-comment.ts
  src/lib/api/board-comment/get-comment.ts
  src/types/board/comment.ts
  src/utils/format-comment-date.ts
  src/utils/scroll-to-top.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#116 ✨ Feat(#109): 팀 초대/참여 API 기능 구현
  src/app/(board)/board/[boardId]/_components/board-detail/copy-team-token.tsx
  src/app/(board-management)/_components/token-input.tsx
  src/app/(team-management)/join-team/_components/join-team-form.tsx
  src/app/(team-management)/join-team/page.tsx
  src/app/[teamId]/_components/member/add-member-modal.tsx
  src/app/[teamId]/_components/member/redirect-board-modal.tsx
  src/lib/api/group/accept-invitation.ts
  src/lib/api/group/create-invitation-token.ts
  src/types/modal-drawer/index.ts
  src/types/team-management/index.ts
  src/utils/get-token-expire.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#118 ✨ Feat(#113): 유저 계정 설정 api 기능 구현
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-component.tsx
  src/app/(auth)/_components/reset-password/reset-password-drawer.tsx
  src/app/(auth)/_components/reset-password/reset-password-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(auth)/_components/user-setting/cancel-user-component.tsx
  src/app/(auth)/_components/user-setting/cancel-user-drawer.tsx
  src/app/(auth)/_components/user-setting/cancel-user-modal.tsx
  src/app/(auth)/_components/user-setting/change-password-component.tsx
  src/app/(auth)/_components/user-setting/change-password-drawer.tsx
  src/app/(auth)/_components/user-setting/change-password-modal.tsx
  src/app/(auth)/_components/user-setting/email-input.tsx
  src/app/(auth)/_components/user-setting/image-input.tsx
  src/app/(auth)/_components/user-setting/name-input.tsx
  src/app/(auth)/_components/user-setting/password-input.tsx
  src/app/(auth)/_components/user-setting/user-setting-form.tsx
  src/app/(auth)/user-setting/page.tsx
  src/app/(team-management)/_components/image-input.tsx
  src/components/nav-bar/gnb-button.tsx
  src/components/nav-bar/logout-component.tsx
  src/components/nav-bar/logout-modal.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/lib/api/auth/sign-up.ts
  src/lib/api/user-setting/cancel-user.ts
  src/lib/api/user-setting/change-password.ts
  src/lib/api/user-setting/edit-user.ts
  src/lib/schemas/auth/index.ts
  src/stores/index.ts
  src/stores/pw-length-atom.ts
  src/types/auth/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#120 ✨ Feat(#86): 팀 페이지 API 연결
  .vscode/settings.json
  public/assets/lotties/team-loading.json
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-nav.tsx
  src/app/[teamId]/_components/team-card/delete-team-modal.tsx
  src/app/[teamId]/_components/team-card/index.tsx
  src/app/[teamId]/_components/todo-list/delete-todo-list-modal.tsx
  src/app/[teamId]/_components/todo-list/edit-todo-list-modal.tsx
  src/app/[teamId]/_components/todo-list/index.tsx
  src/app/[teamId]/_components/todo-list/todo-list-card.tsx
  src/app/[teamId]/_components/todo-list/todo-list-drop-down.tsx
  src/app/[teamId]/layout.tsx
  src/app/[teamId]/page.tsx
  src/app/page.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
  src/components/loading/index.tsx
  src/lib/api/group/delete-group.ts
  src/lib/api/task-list/create-task-list.ts
  src/lib/api/task-list/delete-task-list.ts
  src/lib/api/task-list/edit-task-list.ts
  src/lib/schemas/task-list/index.tsx
  src/types/task-list/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#124 💄 Design: 자유게시판 리스트 페이지 UI 구현
  public/assets/icons/icon-codeit.svg
  public/assets/icons/icon-search.svg
  public/assets/icons/index.ts
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/(board)/boards/_components/board-list-info/board-card.tsx
  src/app/(board)/boards/_components/board-list-info/board-list.tsx
  src/app/(board)/boards/_components/board-list-info/index.tsx
  src/app/(board)/boards/_components/board-list-info/pagination.tsx
  src/app/(board)/boards/_components/board-list-info/search-bar.tsx
  src/app/(board)/boards/_components/board-list-info/test.json
  src/app/(board)/boards/_components/board-list-info/top-title.tsx
  src/app/(board)/boards/_components/carousel.tsx
  src/app/(board)/boards/_data/carouselItems.tsx
  src/app/(board)/boards/page.tsx
  src/app/(board-management)/_components/image-input.tsx
  src/app/(board-management)/board/[boardId]/edit/edit-board-form.tsx
  src/components/common/drop-down/menu.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/constants/board-order-option.ts
  src/constants/image.ts
  src/types/board-list/index.ts
Labels: 우선순위: Medium ☀️, 💄 Design

#126 ✨ Feat(#125): 자유게시판 API 구현
  public/assets/lotties/board-list-empty.json
  src/app/(board)/board/[boardId]/_components/board-detail/board-delete-modal.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/add-comment.tsx
  src/app/(board)/boards/_components/board-list-info/board-card-skeleton.tsx
  src/app/(board)/boards/_components/board-list-info/board-card.tsx
  src/app/(board)/boards/_components/board-list-info/board-empty.tsx
  src/app/(board)/boards/_components/board-list-info/index.tsx
  src/app/(board)/boards/_components/board-list-info/pagination.tsx
  src/app/(board)/boards/_components/board-list-info/search-bar.tsx
  src/app/(board)/boards/_components/board-list-info/test.json
  src/app/(board)/boards/_components/board-list-info/top-title.tsx
  src/app/(board)/boards/_data/carouselItems.tsx
  src/app/(board)/boards/page.tsx
  src/app/(board-management)/board/[boardId]/edit/edit-board-form.tsx
  src/app/(board-management)/create-board/page.tsx
  src/components/common/index.ts
  src/components/common/skeleton-loader/index.tsx
  src/lib/api/board/get-board-list.ts
  src/lib/schemas/board/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#133 ✨ Feat(#119) 카카오 간편 로그인 회원가입 api 연동
  next.config.mjs
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(auth)/_components/user-setting/cancel-user-component.tsx
  src/app/(auth)/_components/user-setting/user-setting-form.tsx
  src/app/(auth)/login/kakao/page.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/components/loading/index.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/logout-component.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/constants/auth-url.ts
  src/lib/api/oauth/kakao-auth.ts
  src/stores/recent-team-atom.ts
  src/stores/user-atom.ts
  src/types/user/index.ts
  src/utils/random-string.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#138 ✨ Feat(##132): 할 일 수정하기
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/description-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/frequency-input.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/layout.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)add-task/page.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-edit.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-header.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-params.ts
  src/app/(list)/[teamId]/task-lists/[listId]/_components/edit-task-modal.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  src/components/loading/index.tsx
  src/constants/frequency.ts
  src/lib/api/task-detail/edit-task-detail.ts
  src/lib/schemas/task/edit-task.tsx
  src/types/task-list/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#135 ✨ Feat(#129): 할일리스트에서 완료기능 추가
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-mutation.ts
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
Labels: ✨ Feat, 우선순위: Medium ☀️

#137 ✨ Feat(#127): 팀 페이지 SSR 변경, 멤버 삭제 구현, 그룹 삭제 시 페이지 이동 구현
  public/assets/images/img-rocket.png
  public/assets/images/img-star.png
  public/assets/lotties/team-empty.json
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/app/[teamId]/_components/member/card.tsx
  src/app/[teamId]/_components/member/index.tsx
  src/app/[teamId]/page.tsx
  src/app/[teamId]/team.json
  src/app/team-empty/page.tsx
  src/app/team/[teamId]/_components/member/add-member-modal.tsx
  src/app/team/[teamId]/_components/member/card.tsx
  src/app/team/[teamId]/_components/member/index.tsx
  src/app/team/[teamId]/_components/member/member-dropdown.tsx
  src/app/team/[teamId]/_components/member/profile-modal.tsx
  src/app/team/[teamId]/_components/member/redirect-board-modal.tsx
  src/app/team/[teamId]/_components/report/circular-progress-bar.tsx
  src/app/team/[teamId]/_components/report/gradient-svg.tsx
  src/app/team/[teamId]/_components/report/index.tsx
  src/app/team/[teamId]/_components/report/todo-count.tsx
  src/app/team/[teamId]/_components/team-card/delete-team-modal.tsx
  src/app/team/[teamId]/_components/team-card/index.tsx
  src/app/team/[teamId]/_components/todo-list/delete-todo-list-modal.tsx
  src/app/team/[teamId]/_components/todo-list/edit-todo-list-modal.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/app/team/[teamId]/_components/todo-list/progress-sign.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-card.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-drop-down.tsx
  src/app/team/[teamId]/layout.tsx
  src/app/team/[teamId]/loading.tsx
  src/app/team/[teamId]/page.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/lib/api/group/delete-member.ts
  src/stores/group-list.ts
  src/utils/extract-group-id.ts
  src/utils/get-team-admin.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#141 ✨ Feat(#140): 채널톡 기능 구현
  src/app/(board)/boards/_components/board-list-info/index.tsx
  src/app/layout.tsx
  src/components/app-provider/index.tsx
  src/components/common/channel-talk/index.tsx
  src/components/nav-bar/team-dropdown.tsx
Labels: ✨ Feat, 우선순위: Medium ☀️

#128 ✨ Feat(#122) 마이히스토리페이지 api 연동
  src/app/user/history/_components/mock.json
  src/app/user/history/_components/my-history-list.tsx
  src/app/user/history/page.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/lib/api/my-history/get-my-history.ts
  src/types/user-history/index.ts
Labels: ✨ Feat, 우선순위: Low 🐢

#145 ✨ Feat(#134): 구글 간편 로그인 회원가입 api 연동
  next.config.mjs
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(auth)/login/google/page.tsx
  src/constants/auth-url.ts
  src/lib/api/axios-instance.ts
  src/lib/api/oauth/google-auth.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#152 🚑️ Fix(#151): 모바일에서 토스트 깜박거리는 현상 수정
  src/components/common/toast/container.tsx
  src/components/common/toast/index.tsx
  tailwind.config.ts
Labels: 🚑️ Fix, 우선순위: Low 🐢

#144 🔨 Refactor(#136): 할일 상세페이지 리팩토링
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-comments.ts
  src/app/(list)/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/page.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#142 ✨ Feat(#139): list-page dnd 라이브러리 적용
  package.json
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  yarn.lock
Labels: ✨ Feat, 우선순위: Medium ☀️

#157 🔨 Refactor(#143): list page query
  src/app/(list)/[teamId]/task-lists/[listId]/_components/edit-task-modal.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/index.ts
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-current.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-date-nav.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/task-lists-nav.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/[teamId]/task-lists/[listId]/page.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/components/common/buttons/add-list-modal-button/index.stories.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
Labels: 우선순위: High 🔥, 🔨 Refactor

#161 🔨 Refactor(#160): list team folder 경로 생성
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/add-task-form.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/calendar.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/date-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/description-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/frequency-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/frequency-sign.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/name-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/select-button.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/weekly-option.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/layout.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/page.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-delete-modal.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-edit.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comments-list.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/empty-comment.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-delete-modal.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-description.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-edit.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-header.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-info.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/index.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-comments.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-mutation.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-params.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/page.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/default.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/calendar-button.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/calendar.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/edit-task-modal.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/index.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-current.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-date-nav.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-lists-nav.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/add-task/page.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/layout.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/page.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/task-detail/[id]/page.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/hooks/index.ts
Labels: 우선순위: High 🔥, 🔨 Refactor

#155 🔨 Refactor(#149): 게시판 리팩토링
  public/assets/icons/icon-banner-words.svg
  public/assets/icons/icon-banner-wywm.svg
  public/assets/icons/index.ts
  src/app/(board)/board/[boardId]/_components/board-detail/board-drop-down.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/empty-comment.tsx
  src/app/(board)/boards/_components/board-list-info/board-card-skeleton.tsx
  src/app/(board)/boards/_components/board-list-info/board-card.tsx
  src/app/(board)/boards/_components/board-list-info/index.tsx
  src/app/(board)/boards/_components/board-list-info/pagination.tsx
  src/app/(board)/boards/_components/board-list-info/top-title.tsx
  src/app/(board)/boards/_components/carousel/carouselItems.tsx
  src/app/(board)/boards/_components/carousel/index.tsx
  src/app/(board)/boards/_data/carouselItems.tsx
  src/app/(board)/boards/page.tsx
  src/app/(board-management)/_components/form-header.tsx
  src/app/(board-management)/_components/image-input.tsx
  src/app/(board-management)/board/[boardId]/edit/edit-board-form.tsx
  src/app/(board-management)/board/[boardId]/edit/page.tsx
  src/app/(board-management)/create-board/page.tsx
  src/app/team/[teamId]/_components/member/member-dropdown.tsx
  src/components/app-provider/index.tsx
  src/components/app-provider/previous-page.tsx
  src/types/board/index.ts
  src/utils/get-random-quote.ts
  src/utils/get-team-admin.ts
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#164 ✨ Feat(#162): tasks dnd 기능
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/lib/api/task-lists/edit-tasks-order.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#158 🔨 Refactor(#156): 팀 생성/수정/참여 리팩토링
  src/app/(team-management)/[teamId]/edit/_components/edit-container.tsx
  src/app/(team-management)/[teamId]/edit/_components/edit-skeleton.tsx
  src/app/(team-management)/[teamId]/edit/page.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/app/(team-management)/_components/image-input.tsx
  src/app/(team-management)/_components/submit-button.tsx
  src/app/(team-management)/create-team/page.tsx
  src/app/(team-management)/join-team/_components/join-team-form.tsx
  src/components/common/index.ts
  src/components/common/tool-tip/index.stories.tsx
  src/components/common/tool-tip/index.tsx
  src/components/loading/index.tsx
  src/lib/schemas/team-manage/index.ts
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#163 🔨 Refactor(#159): 팀 페이지 리팩토링
  public/assets/icons/icon-mail.svg
  public/assets/icons/icon-user-x.svg
  public/assets/icons/index.ts
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/team/[teamId]/_components/member/card.tsx
  src/app/team/[teamId]/_components/member/delete-member-modal.tsx
  src/app/team/[teamId]/_components/member/index.tsx
  src/app/team/[teamId]/_components/report/circular-progress-bar.tsx
  src/app/team/[teamId]/_components/report/index.tsx
  src/app/team/[teamId]/_components/report/progress-provider.tsx
  src/app/team/[teamId]/_components/report/todo-count.tsx
  src/app/team/[teamId]/_components/team-card/delete-team-modal.tsx
  src/app/team/[teamId]/_components/team-card/index.tsx
  src/app/team/[teamId]/_components/todo-list/delete-todo-list-modal.tsx
  src/app/team/[teamId]/page.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#167 🔨 Refactor(#136): 할일 상세관련 리팩토링
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-description.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-edit.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-info.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-mutation.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/page.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/types/group/index.ts
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#154 ✨ Feat(#131): 팀 페이지 drag and drop 기능 구현
  src/app/team/[teamId]/_components/todo-list/drag-and-drop.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-card.tsx
  src/lib/api/task-list/change-task-list.ts
  src/types/task-list/index.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#178 ✨ Feat(#169): middleware 페이지 접근 제한 설정
  src/app/(board)/board/[boardId]/_components/board-detail/board-like.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/copy-team-token.tsx
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/add-comment.tsx
  src/app/(board)/boards/_components/board-list-info/board-card.tsx
  src/app/(team-management)/team/[teamId]/edit/_components/edit-container.tsx
  src/app/(team-management)/team/[teamId]/edit/_components/edit-skeleton.tsx
  src/app/(team-management)/team/[teamId]/edit/page.tsx
  src/app/team/[teamId]/_components/team-card/index.tsx
  src/middleware.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#171 🔨 Refactor(#150): navbar 리팩토링
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(auth)/_components/user-setting/cancel-user-component.tsx
  src/app/(auth)/_components/user-setting/user-setting-form.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/(team-management)/_components/edit-team-form.tsx
  src/app/team/[teamId]/_components/team-card/delete-team-modal.tsx
  src/app/team/[teamId]/_components/team-card/index.tsx
  src/app/team/[teamId]/page.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/logout-component.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/stores/index.ts
  src/stores/recent-team-atom.ts
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#170 🔨 Refactor(#165): lists nav + lists 리팩
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/index.ts
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-lists-nav.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-skeleton.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/page.tsx
  src/app/globals.css
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#184 🚑️ Fix(#177): 댓글 캐밥 안생기던 버그 수정
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comments-list.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_hooks/use-task-comments.ts
  src/types/comments/index.ts
Labels: 🚑️ Fix, 우선순위: High 🔥

#185 🔨 Refactor(#183): 공통 버튼 수정
  src/components/common/buttons/button/index.tsx
  src/components/common/buttons/check-button/index.tsx
  src/components/common/buttons/float-button/index.tsx
  src/components/common/buttons/plus-button/index.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#187 🔨 Refactor(#168): 메타데이타 404 500 페이지
  public/assets/lotties/404.json
  public/assets/lotties/500.json
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/reset-password/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/user-setting/layout.tsx
  src/app/(board)/board/[boardId]/page.tsx
  src/app/(board)/boards/page.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/layout.tsx
  src/app/(team-management)/layout.tsx
  src/app/error.tsx
  src/app/icon.ico
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/team/[teamId]/layout.tsx
  src/app/team/[teamId]/page.tsx
  src/app/user/history/layout.tsx
  src/components/common/drawer/index.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#190 💄 Design(#186): 팀 페이지 UI 개선
  src/app/(board-management)/_components/token-input.tsx
  src/app/team/[teamId]/_components/member/index.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-card.tsx
Labels: 우선순위: Medium ☀️, 💄 Design

#182 ✨ Feat(#176): 구글 애널리틱스 추가
  src/app/layout.tsx
  src/lib/google-analytics/index.tsx
Labels: ✨ Feat, 우선순위: Medium ☀️

#181 📦️ Chore(#179): 오픈 그래프 설정 (정적)
  public/assets/favicon.ico
  public/assets/images/img-open-graph.png
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/sign-up/layout.tsx
  src/app/(board)/board/[boardId]/page.tsx
  src/app/(board)/boards/page.tsx
  src/app/icon.ico
  src/app/layout.tsx
Labels: 📦️ Chore, 우선순위: Medium ☀️

#192 💄 Design(#175): landig for beta
  package.json
  public/assets/lotties/lighting.json
  public/assets/lotties/planet.json
  public/assets/lotties/planet3.json
  public/assets/lotties/rocket.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/landing/buttons.tsx
  src/components/landing/star-canvas.tsx
  yarn.lock
Labels: 우선순위: Medium ☀️, 💄 Design

#189 🔨 Refactor(#172): 계정설정 리팩토링
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/reset-password/reset-password-component.tsx
  src/app/(auth)/_components/reset-password/reset-password-form.tsx
  src/app/(auth)/_components/sign-up/signup-form.tsx
  src/app/(auth)/_components/user-setting/cancel-user-component.tsx
  src/app/(auth)/_components/user-setting/change-password-component.tsx
  src/app/(auth)/_components/user-setting/user-setting-form.tsx
  src/components/nav-bar/logout-component.tsx
  src/lib/api/user-setting/cancel-user.ts
  src/lib/api/user-setting/change-password.ts
  src/lib/api/user-setting/edit-user.ts
  src/lib/schemas/auth/index.ts
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#195 🚑️ Fix(#191): 팀페이지 할 일 목록 요청 후 반영안되는 현상 수정
  src/app/team/[teamId]/_components/member/add-member-modal.tsx
  src/app/team/[teamId]/_components/member/card.tsx
  src/app/team/[teamId]/_components/team-card/index.tsx
  src/app/team/[teamId]/_components/todo-list/delete-todo-list-modal.tsx
  src/app/team/[teamId]/_components/todo-list/drag-and-drop.tsx
  src/app/team/[teamId]/_components/todo-list/edit-todo-list-modal.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-card.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-drop-down.tsx
  src/app/team/[teamId]/page.tsx
  src/app/team/[teamId]/team-wrapper.tsx
  src/components/app-provider/index.tsx
  src/components/common/buttons/add-list-modal-button/index.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#197 🚑️ Fix(#196): 계정설정페이지 이미지만 변경X 수정
  src/app/(auth)/_components/reset-password/reset-password-component.tsx
  src/app/(auth)/_components/user-setting/image-input.tsx
  src/app/(auth)/_components/user-setting/name-input.tsx
  src/app/(auth)/_components/user-setting/user-setting-form.tsx
  src/types/auth/index.ts
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#200 🔨 Refactor(#180): 자유게시판 페이지네이션 및 tanstack query 수정
  public/assets/icons/icon-page-next-next.svg
  public/assets/icons/icon-page-next.svg
  public/assets/icons/icon-page-prev-prev.svg
  public/assets/icons/icon-page-prev.svg
  public/assets/icons/index.ts
  src/app/(board)/boards/_components/board-list-info/index.tsx
  src/app/(board)/boards/_components/board-list-info/pagination.tsx
  src/app/(board)/boards/_components/carousel/carouselItems.tsx
  src/app/(board-management)/create-board/page.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#203 🚑️ Fix(#202): 드롭다운이 팀페이지 할일리스트 오류 수정
  src/app/team/[teamId]/_components/todo-list/todo-list-card.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#205 💄 Design(#204): 네비바 수정
  src/app/(board)/boards/page.tsx
  src/app/(team-management)/join-team/_components/join-team-form.tsx
  src/components/nav-bar/index.tsx
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/user-dropdown.tsx
Labels: 💄 Design, 우선순위: Low 🐢

#210 🚑️ Fix(#208): 이거저거 버그해결
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-description.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-card.tsx
Labels: 🚑️ Fix, 우선순위: High 🔥

#214 🚑️ Fix(#211): date format
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/add-task-form.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/calendar-button.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/calendar.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#217 🚑️ Fix(#215): 글자 수 제한
  src/components/common/buttons/add-list-modal-button/index.tsx
  src/lib/schemas/task-list/index.tsx
  src/lib/schemas/task/edit-task.tsx
  src/lib/schemas/task/index.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#213 ✨ Feat(#212): 반복일정 전체 삭제 기능 추가
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-header.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-card.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/task-delete-modal.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/tasks-container.tsx
  src/lib/api/task-detail/delete-recurring-task.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#223 🚑️ Fix:(#222): 할 일 추가 refresh 이슈 해결
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/add-task-form.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#221 🔨 Refactor(#209): 드롭다운 리팩토링
  src/components/nav-bar/nav-sidebar.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#225 🔨 Refactor(#224): 자유게시판 리팩토링
  src/app/(board)/board/[boardId]/_components/board-detail/board-drop-down.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/index.tsx
  src/app/(board)/boards/_components/board-list-info/index.tsx
  src/app/(board)/boards/_components/board-list-info/top-title.tsx
  src/app/(board)/boards/_components/carousel/carouselItems.tsx
  src/app/(board)/boards/_components/carousel/index.tsx
  src/app/(board)/boards/page.tsx
  src/app/globals.css
  src/components/app-provider/previous-page.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#229 🔨 Refactor(#228): 팀페이지 드래그앤드랍, 드롭다운
  src/app/team/[teamId]/_components/todo-list/drag-and-drop.tsx
  src/app/team/[teamId]/_components/todo-list/index.tsx
  src/app/team/[teamId]/_components/todo-list/todo-list-card.tsx
  src/app/team/[teamId]/team-wrapper.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️, 🔨 Refactor

#235 🔨 Refactor(#230): 로그인/ 계정설정 리팩토링
  next.config.mjs
  src/app/(auth)/_components/login/signin-form.tsx
  src/app/(auth)/_components/user-setting/index.ts
  src/app/(auth)/_components/user-setting/name-input.tsx
  src/app/(auth)/user-setting/page.tsx
  src/app/(auth)/user-setting/user-setting-form.tsx
  src/app/(team-management)/_components/create-team-form.tsx
  src/app/my-teams/page.tsx
  src/app/team/[teamId]/_components/member/delete-member-modal.tsx
  src/app/team/[teamId]/_components/team-card/delete-team-modal.tsx
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
  src/constants/auth-url.ts
  src/constants/frequency.ts
  src/lib/api/auth/sign-in.ts
  src/lib/api/auth/sign-up.ts
  src/lib/api/oauth/google-auth.ts
  src/lib/api/oauth/kakao-auth.ts
  src/utils/validation/.gitkeep
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#232 🛠️Refactor(#173): UI refator
  src/app/(team-management)/_components/image-input.tsx
  src/app/user/history/page.tsx
  src/components/loading/index.tsx
  src/components/nav-bar/team-dropdown.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#238 🔨 Refactor (#237) : 피드백 리팩토링 및 추가기능
  next.config.mjs
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-edit.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comment-input.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/comments/comments-list.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)task-detail/[id]/_components/task-detail/task-content.tsx
  src/components/nav-bar/logout-component.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#244 🚑️ Fix:(#243): 드롭다운 에러 수정
  src/components/nav-bar/team-dropdown.tsx
  src/components/nav-bar/user-dropdown.tsx
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#242 🛠️Refactor(#233) 랜딩 페이지 이미지 변경
  public/assets/images/img-landing-bottom.png
  public/assets/images/img-landing-main.png
  public/assets/images/img-landing-mockup-1.png
  public/assets/images/img-landing-mockup-2.png
  public/assets/images/img-landing-mockup-3.png
  public/assets/images/index.ts
  src/app/page.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#247 🚑️ Fix:(#246): 달력 오류 수정 및 리팩토링
  src/app/(list)/team/[teamId]/task-lists/[listId]/@side/(.)add-task/_components/calendar.tsx
  src/app/(list)/team/[teamId]/task-lists/[listId]/_components/calendar.tsx
  src/constants/weeks.ts
Labels: 🚑️ Fix, 우선순위: Medium ☀️

#245 💄 Design(#236): landing page
  package.json
  public/assets/lotties/alien.json
  public/assets/lotties/planet.json
  public/assets/lotties/planets.json
  public/assets/lotties/rocket.json
  public/assets/lotties/stars.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/landing/buttons.tsx
  src/components/landing/framer-motion-option.ts
  src/components/landing/i-buttons.tsx
  src/components/landing/section1.tsx
  src/components/landing/section2.tsx
  src/components/landing/section3.tsx
  src/components/landing/section4.tsx
  src/components/landing/section5.tsx
  src/components/mouse-trailer/index.tsx
  src/components/nav-bar/logout-component.tsx
  tailwind.config.ts
  yarn.lock
Labels: 우선순위: Medium ☀️, 💄 Design

#249 🔨 Refactor(#248): 리드미 수정
  README.md
Labels: 우선순위: Low 🐢, 🔨 Refactor

#251 🔨 Refactor(#250): 자유게시판 사진 동글동글 및 이거저거
  src/app/(board)/board/[boardId]/_components/board-detail/index.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/comment.tsx
  src/app/(board)/board/[boardId]/_components/comment-list/index.tsx
  src/app/team/[teamId]/_components/member/add-member-modal.tsx
Labels: 우선순위: Medium ☀️, 🔨 Refactor
