Repository sprint6-part4-team3/WouldYouWithMe, pull requests merged in 2024-07, with the labels that each got.

#2 🎉 Init(#1): 초기세팅
  .commitlintrc.json
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .prettierrc
  package-lock.json
  package.json
  src/app/favicon.ico
  src/app/globals.css
  src/app/page.tsx
  tailwind.config.ts
  yarn.lock
Labels: 📦️ Chore

#5 📦️ Chore(#4) : 폴더 세팅 및 이미지세팅
  .eslintrc.json
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package.json
  public/assets/icons/icon-alert.svg
  public/assets/icons/icon-arrow-left.svg
  public/assets/icons/icon-arrow-right.svg
  public/assets/icons/icon-calendar.svg
  public/assets/icons/icon-check-green.svg
  public/assets/icons/icon-check-white.svg
  public/assets/icons/icon-comment.svg
  public/assets/icons/icon-done.svg
  public/assets/icons/icon-gear.svg
  public/assets/icons/icon-img-select.svg
  public/assets/icons/icon-list.svg
  public/assets/icons/icon-plus.svg
  public/assets/icons/icon-profile-desktop.svg
  public/assets/icons/icon-profile.svg
  public/assets/icons/icon-toggle.svg
  public/assets/icons/icon-user.svg
  public/assets/icons/icon-visibility-off.svg
  public/assets/icons/icon-visibility-on.svg
  public/assets/icons/icon-x.svg
  public/assets/images/img-done.png
  public/assets/images/img-google.png
  public/assets/images/img-kakaotalk.png
  public/assets/images/img-todo.png
  public/assets/images/logo-coworkers.png
  public/next.svg
  public/vercel.svg
  src/app/layout.tsx
  src/components/.gitkeep
  src/components/common/.gitkeep
  src/form/.gitkeep
  src/hooks/.gitkeep
  src/types/.gitkeep
  src/utils/validation/.gitkeep
  tsconfig.json
  yarn.lock
Labels: 📦️ Chore

#7 📦️ Chore(#3): Storybook 적용 및 Chromatic 배포
  .eslintrc.json
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .github/workflows/storybook.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  next.config.mjs
  package.json
  public/assets/icons/index.ts
  src/components/.gitkeep
  src/components/common/.gitkeep
  src/components/common/Button/index.stories.tsx
  src/components/common/Button/index.tsx
  src/components/svg.stories.tsx
  yarn.lock
Labels: 📦️ Chore, 우선순위: Medium ☀️

#11 📦️ Chore(#6): Tailwind 스타일 설정 및 폰트 적용
  package.json
  src/app/globals.css
  src/components/common/Button/index.stories.tsx
  src/components/common/Button/index.tsx
  src/components/svg.stories.tsx
  src/stories/colors.mdx
  src/stories/intro.mdx
  src/stories/typography.mdx
  tailwind.config.ts
  yarn.lock
Labels: 📦️ Chore, 우선순위: Medium ☀️

#17 📦️ Chore(#16): Tailwind 타이포그라피 적용
  src/stories/typography.mdx
  tailwind.config.ts
Labels: 📦️ Chore, 우선순위: High 🔥

#13 ✨ Feat(#12): Input 공통 컴포넌트 제작
  src/app/globals.css
  src/components/common/Form/ErrorMessage/index.stories.tsx
  src/components/common/Form/ErrorMessage/index.tsx
  src/components/common/Form/FieldWrapper/index.stories.tsx
  src/components/common/Form/FieldWrapper/index.tsx
  src/components/common/Form/Input/index.stories.tsx
  src/components/common/Form/Input/index.tsx
  src/components/common/Form/Textarea/index.stories.tsx
  src/components/common/Form/Textarea/index.tsx
  src/hooks/useToggle.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#19 ✨ Feat(#18): 드롭다운 공통 컴포넌트 구현
  src/components/common/DropDown/Item.tsx
  src/components/common/DropDown/Menu.tsx
  src/components/common/DropDown/Trigger.tsx
  src/components/common/DropDown/index.stories.tsx
  src/components/common/DropDown/index.tsx
  src/components/common/Form/ErrorMessage/index.stories.tsx
  src/components/common/Form/Input/index.stories.tsx
  src/components/common/Form/Input/index.tsx
  src/components/common/Form/Textarea/index.tsx
  src/hooks/.gitkeep
  src/hooks/useClickOutside.ts
  src/hooks/useToggle.ts
Labels: ✨ Feat, 우선순위: Medium ☀️

#20 ✨Feat(#8) 공용모달컴포넌트
  .eslintrc.json
  src/components/common/modal/common-modal.tsx
  src/components/common/modal/modal.stories.tsx
  tsconfig.json
Labels: ✨ Feat, 우선순위: Medium ☀️

#22 ✨ Feat(#9): navbar 컴포넌트
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/💄-design.md
  .github/ISSUE_TEMPLATE/📦️-chore.md
  .github/ISSUE_TEMPLATE/🔨-refactor.md
  README.md
  public/assets/icons/icon-dropdown.svg
  public/assets/icons/index.ts
  src/components/common/NavBar/index.stories.tsx
  src/components/common/NavBar/index.tsx
Labels: ✨ Feat, 우선순위: Medium ☀️

#25 🔨 Refactor(#24): Tailwind 타이포그라피 설정 파일 이름 변경
  .github/ISSUE_TEMPLATE/🚑️-fix.md
  src/app/layout.tsx
  src/components/common/Button/index.tsx
  src/components/common/Form/error-message/index.stories.tsx
  src/components/common/Form/error-message/index.tsx
  src/components/common/Form/field-wrapper/index.stories.tsx
  src/components/common/Form/field-wrapper/index.tsx
  src/components/common/Form/input/index.stories.tsx
  src/components/common/Form/input/index.tsx
  src/components/common/Form/textarea/index.stories.tsx
  src/components/common/Form/textarea/index.tsx
  src/components/common/drop-down/index.stories.tsx
  src/components/common/drop-down/index.tsx
  src/components/common/drop-down/item.tsx
  src/components/common/drop-down/menu.tsx
  src/components/common/drop-down/trigger.tsx
  src/components/common/modal/index.stories.tsx
  src/components/common/modal/index.tsx
  src/components/common/nav-bar/index.stories.tsx
  src/components/common/nav-bar/index.tsx
  src/hooks/use-click-outside.ts
  src/hooks/use-toggle.ts
  src/stories/svg.stories.tsx
  tailwind.config.ts
  yarn.lock
Labels: 우선순위: Medium ☀️, 🔨 Refactor

#26 ✨ Feat(#15): icon button 컴포넌트
  .vscode/settings.json
  public/assets/icons/declartions.d.ts
  src/components/common/icon-button/index.stories.tsx
  src/components/common/icon-button/index.tsx
Labels: ✨ Feat, 우선순위: Medium ☀️

#31 ✨ Feat(#28): framer motion component
  src/components/common/framer-motion/animate-presence/index.tsx
  src/components/common/framer-motion/motion/index.stories.tsx
  src/components/common/framer-motion/motion/index.tsx
Labels: ✨ Feat, 우선순위: Low 🐢

#30 ✨ Feat(#10) side menu 제작
  src/components/common/drop-down/menu.tsx
  src/components/common/nav-bar/index.stories.tsx
  src/components/common/nav-bar/index.tsx
  src/components/common/nav-bar/nav-component.tsx
Labels: ✨ Feat, 우선순위: Medium ☀️

#33 ✨ Feat(#32): Toast 컴포넌트 구현
  package.json
  public/assets/lotties/error.json
  public/assets/lotties/success.json
  src/app/layout.tsx
  src/components/common/forms/error-message/index.stories.tsx
  src/components/common/forms/error-message/index.tsx
  src/components/common/forms/field-wrapper/index.stories.tsx
  src/components/common/forms/field-wrapper/index.tsx
  src/components/common/forms/input/index.stories.tsx
  src/components/common/forms/input/index.tsx
  src/components/common/forms/textarea/index.stories.tsx
  src/components/common/forms/textarea/index.tsx
  src/components/common/toast/container.tsx
  src/components/common/toast/index.stories.tsx
  src/components/common/toast/index.tsx
  src/hooks/use-toast.ts
  src/stores/toast.ts
  yarn.lock
Labels: ✨ Feat, 우선순위: Low 🐢

#42 📦️ Chore(#41): 서버컴포넌트에서 svgr 사용세팅
  next.config.mjs
  svgr.d.ts
  tsconfig.json
Labels: 📦️ Chore, 우선순위: High 🔥

#39 ✨ Feat(#35): 로그인페이지 제작
  .gitignore
  public/assets/images/index.ts
  src/app/(auth)/_components/signin-form.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/actions.ts
  src/app/(auth)/login/page.tsx
  src/components/common/index.ts
  src/lib/api/axios-instance.ts
  src/lib/schemas/auth.ts
  src/types/.gitkeep
  src/types/auth.ts
Labels: ✨ Feat, 우선순위: High 🔥

#40 💄 Design(#34): 팀 페이지 리포트, 멤버 UI 구현
  package.json
  public/assets/icons/icon-done-panel.svg
  public/assets/icons/icon-plus-current.svg
  public/assets/icons/icon-profile-current.svg
  public/assets/icons/icon-todo.svg
  public/assets/icons/index.ts
  src/app/[teamId]/_components/member/add-member-modal.tsx
  src/app/[teamId]/_components/member/card.tsx
  src/app/[teamId]/_components/member/index.tsx
  src/app/[teamId]/_components/member/profile-modal.tsx
  src/app/[teamId]/_components/report/circular-progress-bar.tsx
  src/app/[teamId]/_components/report/gradient-svg.tsx
  src/app/[teamId]/_components/report/index.tsx
  src/app/[teamId]/_components/report/todo-count.tsx
  src/app/[teamId]/layout.tsx
  src/app/[teamId]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/drop-down/index.stories.tsx
  src/components/common/drop-down/index.tsx
  src/components/common/forms/input/index.tsx
  src/components/common/nav-bar/nav-component.tsx
  src/components/common/toast/container.tsx
  src/components/common/toast/index.stories.tsx
  src/components/common/toast/index.tsx
  src/hooks/index.ts
  src/hooks/use-is-mobile.ts
  src/hooks/use-toggle.ts
  yarn.lock
Labels: 우선순위: Medium ☀️, 💄 Design

#45 Design(#37) 리스트 UI 제작
  package.json
  public/assets/icons/icon-calendar.svg
  public/assets/icons/icon-checkbox-green.svg
  public/assets/icons/icon-checkbox.svg
  public/assets/icons/icon-kebab.svg
  public/assets/icons/icon-repeat.svg
  public/assets/icons/icon-time.svg
  public/assets/icons/index.ts
  src/app/list/_components/mock.json
  src/app/list/_components/tasks-card.tsx
  src/app/list/_components/tasks-container.tsx
  src/app/list/page.tsx
  src/types/task-list/index.ts
  yarn.lock
Labels: 우선순위: Medium ☀️, 💄 Design
